/*
 * @Descripttion:
 * @Author: 李峥
 * @Date: 2022-12-15 21:48:34
 * @LastEditors: 李峥
 * @LastEditTime: 2022-12-16 21:34:14
 */
export const list: any = [
  {
    type: "addApp",
    name: "添加应用",
    id: "addApp",
    img: "https://files.codelife.cc/website/add.svg",
    url: "",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
  {
    type: "app",
    name: "app名称",
    id: "appID",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
  },
];
