/*
 * @Descripttion:
 * @Author: 李峥
 * @Date: 2022-12-15 21:48:34
 * @LastEditors: 李峥
 * @LastEditTime: 2022-12-21 18:08:45
 */
export const list: any = [
  {
    type: "systemApp",
    name: "i天气",
    componentsName: "weather",
    id: "systemApp",
    img: "",
    url: "",
    layout: "2X4",
  },
  // {
  //   type: "systemApp",
  //   name: "文件夹",
  //   componentsName: "folder",
  //   id: "folder",
  //   img: "",
  //   url: "",
  //   layout: "2X2",
  // },
  {
    type: "addApp",
    name: "添加应用",
    componentsName: "smallWeb",
    id: "addApp",
    img: "https://files.codelife.cc/website/add.svg",
    url: "",
    layout: "1X1",
  },
  {
    type: "app",
    name: "GitHub",
    componentsName: "smallWeb",
    id: "001",
    img: "https://files.codelife.cc/website/github.svg",
    url: "https://github.com/",
    layout: "1X1",
    color: "#fff",
  },
  {
    type: "app",
    name: "MDN",
    componentsName: "smallWeb",
    id: "002",
    img: "https://files.codelife.cc/website/mdn-web-docs.svg",
    url: "https://developer.mozilla.org/zh-CN/docs/Learn",
    layout: "1X1",
    color: "#fff",
  },
  {
    type: "app",
    name: "V2EX",
    componentsName: "smallWeb",
    id: "003",
    img: "https://files.codelife.cc/website/v2ex.svg",
    url: "http://www.v2ex.com/",
    layout: "1X1",
    color: "#fff",
  },
  {
    type: "app",
    name: "React",
    componentsName: "smallWeb",
    id: "004",
    img: "https://files.codelife.cc/website/react.svg",
    url: "https://zh-hans.reactjs.org/",
    layout: "1X1",
    color: "#fff",
  },
  {
    type: "app",
    name: "Java学习",
    componentsName: "smallWeb",
    id: "005",
    img: "https://files.codelife.cc/website/mrjokersince-java.svg",
    url: "https://mrjokersince1997.github.io/My-Notes/#/",
    layout: "1X1",
    color: "#fff",
  },
  {
    type: "app",
    name: "nuxtjs",
    componentsName: "smallWeb",
    id: "006",
    img: "https://files.codelife.cc/website/nuxtjs.svg",
    url: "https://nuxtjs.org/",
    layout: "1X1",
    color: "#fff",
  },
  {
    type: "app",
    name: "Electron",
    componentsName: "smallWeb",
    id: "007",
    img: "https://files.codelife.cc/website/electronjs.svg",
    url: "https://electronjs.org/",
    layout: "1X1",
    color: "#fff",
  },
  {
    type: "app",
    name: "码云Gitee",
    componentsName: "smallWeb",
    id: "013",
    img: "https://files.codelife.cc/website/gitee.svg",
    url: "https://gitee.com/",
    layout: "1X1",
    color: "#fff",
  },
  {
    type: "app",
    name: "CSDN",
    componentsName: "smallWeb",
    id: "014",
    img: "https://files.codelife.cc/website/csdn.svg",
    url: "http://www.csdn.net/",
    layout: "1X1",
    color: "#fff",
  },
  {
    type: "app",
    name: "Vite",
    componentsName: "smallWeb",
    id: "015",
    img: "https://files.codelife.cc/website/vitejs.svg",
    url: "https://vitejs.dev/",
    layout: "1X1",
    color: "#fff",
  },
  {
    type: "app",
    name: "Vue2",
    componentsName: "smallWeb",
    id: "016",
    img: "https://files.codelife.cc/website/vuejs.svg",
    url: "https://cn.vuejs.org/",
    layout: "1X1",
    color: "#fff",
  },
  {
    type: "app",
    name: "element-ui",
    componentsName: "smallWeb",
    id: "017",
    img: "https://files.codelife.cc/website/elementui.svg",
    url: "https://element.eleme.cn/#/zh-CN",
    layout: "1X1",
    color: "#fff",
  },
  {
    type: "app",
    name: "Element Plus",
    componentsName: "smallWeb",
    id: "018",
    img: "https://element-plus.gitee.io/images/element-plus-logo-small.svg",
    url: "https://element-plus.gitee.io/zh-CN/",
    layout: "1X1",
    color: "#fff",
  },
  {
    type: "app",
    name: "app名称",
    componentsName: "smallWeb",
    id: "019",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
    layout: "1X1",
    color: "#fff",
  },
  {
    type: "app",
    name: "app名称",
    componentsName: "smallWeb",
    id: "020",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
    layout: "1X1",
    color: "#fff",
  },
  {
    type: "app",
    name: "app名称",
    componentsName: "smallWeb",
    id: "021",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
    layout: "1X1",
    color: "#fff",
  },
];
