/*
 * @Descripttion:
 * @Author: 李峥
 * @Date: 2022-12-15 21:48:34
 * @LastEditors: 李峥
 * @LastEditTime: 2022-12-18 00:47:03
 */
export const list: any = [
  {
    type: "systemApp",
    name: "i天气",
    componentsName: "weather",
    id: "systemApp",
    img: "",
    url: "",
    layout: "2*4",
  },
  {
    type: "systemApp",
    name: "文件夹",
    componentsName: "folder",
    id: "folder",
    img: "",
    url: "",
    layout: "2*2",
  },
  {
    type: "addApp",
    name: "添加应用",
    componentsName: "smallWeb",
    id: "addApp",
    img: "https://files.codelife.cc/website/add.svg",
    url: "",
    layout: "1*1",
  },
  {
    type: "app",
    name: "app名称1",
    componentsName: "smallWeb",
    id: "001",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
    layout: "1*1",
  },
  {
    type: "app",
    name: "app名称2",
    componentsName: "smallWeb",
    id: "002",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
    layout: "1*1",
  },
  {
    type: "app",
    name: "app名称3",
    componentsName: "smallWeb",
    id: "003",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
    layout: "1*1",
  },
  {
    type: "app",
    name: "app名称4",
    componentsName: "smallWeb",
    id: "004",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
    layout: "1*1",
  },
  {
    type: "app",
    name: "app名称5",
    componentsName: "smallWeb",
    id: "005",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
    layout: "1*1",
  },
  {
    type: "app",
    name: "app名称6",
    componentsName: "smallWeb",
    id: "006",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
    layout: "1*1",
  },
  {
    type: "app",
    name: "app名称",
    componentsName: "smallWeb",
    id: "007",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
    layout: "1*1",
  },
  {
    type: "app",
    name: "app名称",
    componentsName: "smallWeb",
    id: "008",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
    layout: "1*1",
  },
  {
    type: "app",
    name: "app名称",
    componentsName: "smallWeb",
    id: "009",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
    layout: "1*1",
  },
  {
    type: "app",
    name: "app名称",
    componentsName: "smallWeb",
    id: "010",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
    layout: "1*1",
  },
  {
    type: "app",
    name: "app名称",
    componentsName: "smallWeb",
    id: "011",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
    layout: "1*1",
  },
  {
    type: "app",
    name: "app名称",
    componentsName: "smallWeb",
    id: "012",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
    layout: "1*1",
  },
  {
    type: "app",
    name: "app名称",
    componentsName: "smallWeb",
    id: "013",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
    layout: "1*1",
  },
  {
    type: "app",
    name: "app名称",
    componentsName: "smallWeb",
    id: "014",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
    layout: "1*1",
  },
  {
    type: "app",
    name: "app名称",
    componentsName: "smallWeb",
    id: "015",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
    layout: "1*1",
  },
  {
    type: "app",
    name: "app名称",
    componentsName: "smallWeb",
    id: "016",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
    layout: "1*1",
  },
  {
    type: "app",
    name: "app名称",
    componentsName: "smallWeb",
    id: "017",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
    layout: "1*1",
  },
  {
    type: "app",
    name: "app名称",
    componentsName: "smallWeb",
    id: "018",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
    layout: "1*1",
  },
  {
    type: "app",
    name: "app名称",
    componentsName: "smallWeb",
    id: "019",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
    layout: "1*1",
  },
  {
    type: "app",
    name: "app名称",
    componentsName: "smallWeb",
    id: "020",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
    layout: "1*1",
  },
  {
    type: "app",
    name: "app名称",
    componentsName: "smallWeb",
    id: "021",
    img: "https://files.codelife.cc/website/jsdesign.svg",
    url: "https://js.design/square?sort=downloadNum&source=itab&plan=4",
    layout: "1*1",
  },
];
